import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import * as CFB from "cfb";
import { zipSync, strToU8, deflateSync } from "fflate";
const require = createRequire(import.meta.url);
const workerRequire = createRequire(require.resolve("wrangler/package.json"));
const { build } = workerRequire("esbuild");
await mkdir(".sites-runtime", { recursive: true });
await build({ stdin: { contents: 'export * from "./lib/mybox/credentials"; export * from "./lib/mybox/client"; export * from "./lib/mybox/extract"; export * from "./lib/mybox/errors"; export * from "./lib/mybox/mcp"; export * from "./lib/mybox/tools";', resolveDir: process.cwd(), loader: "ts" }, bundle: true, packages: "external", platform: "node", format: "esm", outfile: ".sites-runtime/mybox-core.mjs" });
const core = await import(path.resolve(".sites-runtime/mybox-core.mjs"));
const key = Buffer.alloc(32, 27).toString("base64");
const PAT = "mbx_pat_test_1234567890";
let tests = 0;
async function check(title, task) { await task(); tests++; console.log(`PASS ${title}`); }
const rows = new Map();
const env = { MYBOX_TOKEN_ENCRYPTION_KEY: key, DB: { prepare(sql) { return { bind(...values) { return { async first() { return sql.includes("FROM mybox_connections") ? rows.get(values[0]) || null : null; }, async run() { if (sql.startsWith("DELETE")) rows.delete(values[0]); else rows.set(values[0], { encrypted_token: values[1], connected_at: values[2] }); } }; } }; } } };
const rpc = (method, params = {}, auth = true, id = 1, extra = {}) => new Request("https://mybox.example/mcp", { method: "POST", headers: { "content-type": "application/json", ...(auth ? { "oai-authenticated-user-id": "alice", "oai-authenticated-user-email": "alice@example.com" } : {}), ...extra }, body: JSON.stringify({ jsonrpc: "2.0", ...(id !== undefined ? { id } : {}), method, params }) });
await check("credentials encrypted, randomized and bound to user", async () => { const a = await core.sealToken(PAT, "alice", key); const b = await core.sealToken(PAT, "alice", key); assert.notEqual(a, b); assert(!a.includes(PAT)); assert.equal(await core.openToken(a, "alice", key), PAT); await assert.rejects(core.openToken(a, "bob", key)); });
await check("connections are isolated per user and status contains no token", async () => { await core.saveToken(env, "alice", PAT); assert.equal(await core.getToken(env, "alice"), PAT); await assert.rejects(core.getToken(env, "bob")); const status = await core.connectionStatus(env, "alice"); assert(status.connected); assert(!JSON.stringify(status).includes(PAT)); });
await check("MCP initialization and discovery expose read and management tools", async () => { const response = await core.handleMcp(rpc("initialize", { protocolVersion: "2025-03-26" }, false), env); assert.equal((await response.json()).result.protocolVersion, "2025-03-26"); const tools = (await (await core.handleMcp(rpc("tools/list", {}, false), env)).json()).result.tools; assert.equal(tools.length, 22); assert(tools.find(t => t.name === "fetch").annotations.readOnlyHint); assert(tools.find(t => t.name === "delete_resource").annotations.destructiveHint); assert(!JSON.stringify(tools).includes(PAT)); });
await check("unauthenticated MCP tools cannot access private data", async () => { const response = await core.handleMcp(rpc("tools/call", { name: "get_connection_status" }, false), env); assert.equal(response.status, 401); });
await check("MCP status tool works and returns no credential", async () => { const body = await (await core.handleMcp(rpc("tools/call", { name: "get_connection_status" }), env)).json(); assert(body.result.structuredContent.connected); assert(!JSON.stringify(body).includes(PAT)); });
await check("MCP malformed JSON and cross-origin requests fail intentionally", async () => { const invalid = new Request("https://mybox.example/mcp", { method: "POST", headers: { "content-type": "application/json" }, body: "{" }); assert.equal((await (await core.handleMcp(invalid, env)).json()).error.code, -32700); assert.equal((await core.handleMcp(rpc("tools/list", {}, true, 1, { origin: "https://other.example" }), env)).status, 403); });
await check("unknown methods and prototype tool names are rejected", async () => { assert.equal((await core.handleMcp(rpc("nothing"), env)).status, 404); await assert.rejects(core.executeTool("toString", {}, env, "alice", "https://mybox.example"), e => e.code === "UNKNOWN_TOOL"); });
await check("signed download does not receive PAT; unsafe redirects blocked", async () => { const calls = []; const client = new core.MyboxClient(PAT, async (url, init) => { calls.push({ url: String(url), init }); const u = new URL(url); if (u.hostname.startsWith("storage")) return new Response("hello"); if (u.pathname.endsWith("/download")) return Response.json({ downloadUrl: "https://storage.mybox.naver.com/v1/download?atoken=signed" }); return Response.json({ resourceId: "file1", name: "hello.txt", type: "file", size: 5 }); }); assert.equal(new TextDecoder().decode((await client.download("file1")).bytes), "hello"); assert(calls[0].init.headers.Authorization.includes(PAT)); assert(!calls[2].init.headers); assert.throws(() => core.safeDownloadUrl("https://naver.com.evil.example/file")); assert.throws(() => core.safeDownloadUrl("http://127.0.0.1/file")); const redirecting = new core.MyboxClient(PAT, async url => new URL(url).hostname.startsWith("storage") ? new Response(null, { status: 302, headers: { location: "https://evil.example/" } }) : new URL(url).pathname.endsWith("/download") ? Response.json({ downloadUrl: "https://storage.mybox.naver.com/file" }) : Response.json({ resourceId: "file1", name: "test.txt", type: "file", size: 1 })); await assert.rejects(redirecting.download("file1"), e => e.code === "BAD_DOWNLOAD_URL"); });
await check("MYBOX pagination, folder IDs and search query parameters match official API", async () => { const calls = []; const client = new core.MyboxClient(PAT, async (url, init) => { calls.push(new URL(url)); assert(!init.method || init.method === "GET"); return Response.json({ resources: [{ resourceId: "id1", name: "미분.txt" }], responseMetaData: { nextCursor: "next" } }); }); const result = await core.executeTool("search", { query: "미분", cursor: "before", count: 20 }, env, "alice", "https://mybox.example", client); assert.equal(result.next_cursor, "next"); assert.equal(calls[0].pathname, "/v1/search/resources/files"); assert.equal(calls[0].searchParams.get("q"), "미분"); await client.list("opaque/id+", "next"); assert.equal(calls[1].pathname, "/v1/drive/folders/opaque%2Fid%2B/resources"); assert.equal(calls[1].searchParams.get("cursor"), "next"); await assert.rejects(core.executeTool("search", { query: "x", count: 1 }, env, "alice", "https://mybox.example", client)); });
await check("bounded response reading rejects excessive content", async () => { await assert.rejects(core.limitedBytes(new Response("a".repeat(1025)), 1024)); await assert.rejects(core.limitedBytes(new Response("x", { headers: { "content-length": "2048" } }), 1024)); });
await check("DOCX and HWPX extract Korean paragraphs and equation scripts", async () => { const docx = zipSync({ "word/document.xml": strToU8('<w:document><w:p><w:r><w:t>미분 &amp; 함수</w:t></w:r></w:p></w:document>') }); assert.equal((await core.extractDocument("test.docx", docx)).text, "미분 & 함수"); const hwpx = zipSync({ "Contents/section0.xml": strToU8('<hp:section><hp:p><hp:run><hp:t>접선</hp:t><hp:equation><hp:script>x^2</hp:script></hp:equation></hp:run></hp:p></hp:section>') }); const text = (await core.extractDocument("test.hwpx", hwpx)).text; assert(text.includes("접선")); assert(text.includes("x^2")); });
function hwpBytes(compressed) { const text = Buffer.from("미분 자료 ABC\r", "utf16le"); const record = Buffer.alloc(4 + text.length); record.writeUInt32LE((text.length << 20) | 67); text.copy(record, 4); const header = Buffer.alloc(256); header.write("HWP Document File"); header.writeUInt32LE(0x05000000, 32); header.writeUInt32LE(compressed ? 1 : 0, 36); const cfb = CFB.utils.cfb_new(); CFB.utils.cfb_add(cfb, "FileHeader", header); CFB.utils.cfb_add(cfb, "BodyText/Section0", compressed ? deflateSync(record) : record); return new Uint8Array(CFB.write(cfb, { type: "array" })); }
await check("HWP 5 compressed and uncompressed body text", async () => { for (const compressed of [false, true]) assert.equal((await core.extractDocument("test.hwp", hwpBytes(compressed))).text, "미분 자료 ABC"); });
await check("document extraction rejects ZIP bombs, corrupt HWP and unsupported formats", async () => { const bomb = zipSync({ "word/document.xml": strToU8("a".repeat(8 * 1024 * 1024 + 1)) }); await assert.rejects(core.extractDocument("bomb.docx", bomb), e => e.code === "TOO_COMPLEX"); await assert.rejects(core.extractDocument("broken.hwp", strToU8("invalid"))); await assert.rejects(core.extractDocument("image.png", strToU8("x")), e => e.code === "UNSUPPORTED_FORMAT"); });
function makePDF() { const objects = ['<< /Type /Catalog /Pages 2 0 R >>', '<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << /Font << /F1 5 0 R >> >> /Contents 6 0 R >>', '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << /Font << /F1 5 0 R >> >> /Contents 7 0 R >>', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>']; for (const text of ["Hello derivative 123", "Second page 456"]) { const stream = `BT /F1 12 Tf 30 240 Td (${text}) Tj ET`; objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`); } let pdf = "%PDF-1.4\n"; const positions = [0]; objects.forEach((value, i) => { positions.push(pdf.length); pdf += `${i + 1} 0 obj\n${value}\nendobj\n`; }); const xref = pdf.length; pdf += `xref\n0 ${positions.length}\n0000000000 65535 f \n`; for (const position of positions.slice(1)) pdf += `${String(position).padStart(10, "0")} 00000 n \n`; pdf += `trailer\n<< /Size ${positions.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return strToU8(pdf); }
const pdf = makePDF();
await check("PDF extraction reads selected pages and reports continuation", async () => { const first = await core.extractDocument("test.pdf", pdf.slice(), { pageCount: 1 }); assert.equal(first.totalPages, 2); assert.equal(first.nextStartPage, 2); assert(first.text.includes("Hello derivative 123")); const second = await core.extractDocument("test.pdf", pdf.slice(), { startPage: 2, pageCount: 1 }); assert(second.text.includes("Second page 456")); assert.equal(second.nextStartPage, null); });
await check("disconnect removes only the current user's credential", async () => { await core.saveToken(env, "bob", PAT); await core.disconnect(env, "alice"); assert(!(await core.connectionStatus(env, "alice")).connected); assert((await core.connectionStatus(env, "bob")).connected); });

// Run the actual parsing, cryptography and MCP logic inside Cloudflare workerd.
const { Miniflare } = workerRequire("miniflare");
await build({ stdin: { contents: 'import {handleMcp} from "./lib/mybox/mcp"; import {extractDocument} from "./lib/mybox/extract"; import {saveToken} from "./lib/mybox/credentials"; export default {async fetch(request,env){let u=new URL(request.url); if(u.pathname==="/test/pdf") return Response.json(await extractDocument("fixture.pdf", new Uint8Array(await request.arrayBuffer()),{pageCount:1})); if(u.pathname==="/test/save"){await saveToken(env,"alice","mbx_pat_test_1234567890");return Response.json({saved:true});}return handleMcp(request,env);}};', resolveDir: process.cwd(), loader: "ts" }, bundle: true, platform: "browser", format: "esm", target: "es2022", external: ["node:*"], outfile: ".sites-runtime/mybox-worker.mjs" });
const mf = new Miniflare({ modules: true, scriptPath: path.resolve(".sites-runtime/mybox-worker.mjs"), compatibilityDate: "2026-05-15", compatibilityFlags: ["nodejs_compat"], bindings: { MYBOX_TOKEN_ENCRYPTION_KEY: key }, d1Databases: ["DB"] });
try {
  const db = await mf.getD1Database("DB");
  for (const file of ["drizzle/0000_breezy_karen_page.sql", "drizzle/0001_wide_post.sql"]) for (const sql of (await readFile(file, "utf8")).split("--> statement-breakpoint").filter(s => s.trim())) await db.prepare(sql).run();
  await check("Cloudflare runtime: D1 encrypted connection and authenticated MCP", async () => { assert.equal((await mf.dispatchFetch("https://mybox.example/test/save")).status, 200); const request = rpc("tools/call", { name: "get_connection_status" }); const response = await mf.dispatchFetch(request.url, { method: request.method, headers: request.headers, body: await request.text() }); const data = await response.json(); assert(data.result.structuredContent.connected); assert(!JSON.stringify(data).includes(PAT)); });
  await check("Cloudflare runtime: PDF parsing and cleanup", async () => { const response = await mf.dispatchFetch("https://mybox.example/test/pdf", { method: "POST", body: pdf }); const data = await response.json(); assert(data.text.includes("Hello derivative 123")); assert.equal(data.nextStartPage, 2); });
} finally { await mf.dispose(); }
console.log(`Verified ${tests} checks.`);
